### ISSUE TITLE
Create database if not exists

### ISSUE THREAD

**Issue by canadaduane** [aboviq/emigrate#147]
I may be spoiled by Prisma, but my first error when running migrations locally was "database does not exist".

Since the user has the correct permission to create the database, could we automate that step?

**Comment by joakimbeng** [comment]
I see! Usually in my setups (at least in production environments) my database user does not have the permission to create databases.

But I guess it would be possible to at least try to create it if it doesn't exist already. Which database are you using?

**Comment by joakimbeng** [comment]
This is supported both in the MySQL and Postgres plugins now, in their 0.3.0 versions respectively.

Thanks for the suggestion, @canadaduane !
